### ISSUE TITLE
Not working in iphone safari browser

### ISSUE THREAD

**Issue by vikassingla** [TwilioDevEd/browser-calls-node#1]
I have successsfully setup the demo on my live server that is using http protocol. 
Now I am testing it on all the platforms to check whether it meets my requirements or not. I am facing problem
on ios mobile browsers.

My requirement is to make conference call demo on both browsers to phone and phone to browser  and  and it must work on all platforms including cordova apps.

Could you please suggest me some examples or solution of my problem. 

Thanks

**Comment by mcelicalderon** [comment]
Hey @vikassingla !

Currently v1.3 of the [Twilio Client JS SDK](https://www.twilio.com/docs/api/client/twilio-js) only supports chrome, firefox and Edge browsers. Please refer to [this](https://www.twilio.com/help/faq/twilio-client/which-browsers-support-webrtc) for more information on the subject. I would recommend downgrading the Twilio client to v1.2 which is supported in Safari as it uses Flash (won't work for mobile versions of Safari), or stick to the other browsers for web clients and use a Twilio mobile native SDK for [android](https://www.twilio.com/docs/api/client/android) and [iOS](https://www.twilio.com/docs/api/client/ios).

In order to meet your requirements (making a conference call between mobile devices and web browsers), you would definitively need to create a simple android or iOS application as no mobile browser is currently supported for the JS client.

Let us know if we can be of further assistance.

**Comment by vikassingla** [comment]
I have created demo using this repository. Now i want to make conference call between users could you please suggest me how to make it possible.

**Comment by mcelicalderon** [comment]
Hey @vikassingla !

Having a conference call with Twilio is very easy! You can have a conference call between people calling from a phone to a Twilio number, from supported browsers (very much like in this example application) and from mobile applications using the mobile SDKs to create native voice apps.

The simplest scenario is to configure one of your Twilio number to make a request to a server side application that will use [TwiML](https://www.twilio.com/docs/api/twiml) to instruct the callers to join a conference room so they can all talk. Please take a look at this tutorial for a simple demonstration on how to set up a number where people can join a conference [Conference Tutorial](https://www.twilio.com/docs/tutorials/walkthrough/conference-broadcast/php/laravel).

You can also take a look at this tutorial ([Warm Transfers](https://www.twilio.com/docs/tutorials/walkthrough/warm-transfer/ruby/rails)) where users can join the same conference room from a regular phone and also from a web browser.

If you need further assistance please [contact support](https://www.twilio.com/help/contact) so they can help you if you need more information on how to build your solution.
